FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@9.0.0 && pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter @kicksmtaani/api build

EXPOSE 4000

CMD ["pnpm", "--filter", "@kicksmtaani/api", "dev"]
